<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Sophon.UI</RootNamespace>
    <AssemblyName>Sophon.UI</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Sophon.Contracts\Sophon.Contracts.csproj" />
    <ProjectReference Include="..\Sophon.Infrastructure\Sophon.Infrastructure.csproj" />
    <ProjectReference Include="..\Sophon.Motion\Sophon.Motion.csproj" />
    <ProjectReference Include="..\Sophon.Core\Sophon.Core.csproj" />
    <ProjectReference Include="..\Sophon.Application\Sophon.Application.csproj" />
    <ProjectReference Include="..\Sophon.Vision\Sophon.Vision.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="Prism.Container.DryIoc" Version="9.0.106" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
    <PackageReference Include="Nodify" Version="7.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>