<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Sophon.Core</RootNamespace>
    <AssemblyName>Sophon.Core</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Sophon.Contracts\Sophon.Contracts.csproj" />
    <ProjectReference Include="..\Sophon.Infrastructure\Sophon.Infrastructure.csproj" />
    <ProjectReference Include="..\Sophon.Motion\Sophon.Motion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

</Project>