<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Sophon.Infrastructure</RootNamespace>
    <AssemblyName>Sophon.Infrastructure</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Sophon.Contracts\Sophon.Contracts.csproj" />
    <ProjectReference Include="..\Sophon.Motion\Sophon.Motion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DryIoc.dll" Version="5.4.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="NModbus.Serial" Version="3.0.81" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="6.2.485" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="8.0.1" />
    <PackageReference Include="System.Reactive" Version="6.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.221" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

</Project>